### ISSUE TITLE
ts-web/core release roadmap

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-sdk#7]
## prereqs
- [x] "documentation" :hand_over_mouth: #4 
- [x] license #6 

## intermediate release: share with our developer partners
- [x] ~~add read permission on github~~

## middle phase
- [ ] (add further discovered tasks here)

## public release
- [ ] bump version to 1.0.0
- [x] flip this repo public
- [x] create npm repos
- [x] build and upload to npm
- [x] ~~clean up allowed readers~~

**Comment by pro-wh** [comment]
all that's left is the 1.0.0. but let's track that in #69
